Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 67, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 33, in generate_pdf
    logger.debug()
TypeError: Logger.debug() missing 1 required positional argument: 'msg'
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 67, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 33, in generate_pdf
    logger.debug("hi")
    ^^^^^^^^^^^^^^
TypeError: Logger.debug() missing 1 required positional argument: 'msg'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 66, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 36, in generate_pdf
    e = element.cleaned_data['element']
        ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'cleaned_data'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 66, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 38, in generate_pdf
    mytable.append(datas[int(i)])
                   ~~~~~^^^^^^^^
KeyError: 0
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 67, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 39, in generate_pdf
    mytable.append(datas[int(i)])
                   ~~~~~^^^^^^^^
KeyError: 0
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 67, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 39, in generate_pdf
    mytable.append(datas[int(i)])
                   ~~~~~^^^^^^^^
KeyError: 0
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 67, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 54, in generate_pdf
    pdf.build([table])
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1082, in build
    self.handle_flowable(flowables)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 931, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/frames.py", line 169, in _add
    w, h = flowable.wrap(aW, h)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 1317, in wrap
    self._calc(availWidth, availHeight)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 732, in _calc
    self._calc_height(availHeight,availWidth,W=W)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 656, in _calc_height
    dW,t = self._listCellGeom(v,w or self._listValueWidth(v),s)
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 508, in _listValueWidth
    return max([v.wrapOn(canv,aW,aH)[0] for v in V])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 508, in <listcomp>
    return max([v.wrapOn(canv,aW,aH)[0] for v in V])
                ^^^^^^^^
AttributeError: 'str' object has no attribute 'wrapOn'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 67, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 39, in generate_pdf
    mytable.append(datas.str(i+1))
                   ^^^^^^^^^
AttributeError: 'dict' object has no attribute 'str'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 67, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 54, in generate_pdf
    pdf.build([table])
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1082, in build
    self.handle_flowable(flowables)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 931, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/frames.py", line 169, in _add
    w, h = flowable.wrap(aW, h)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 1317, in wrap
    self._calc(availWidth, availHeight)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 732, in _calc
    self._calc_height(availHeight,availWidth,W=W)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 656, in _calc_height
    dW,t = self._listCellGeom(v,w or self._listValueWidth(v),s)
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 508, in _listValueWidth
    return max([v.wrapOn(canv,aW,aH)[0] for v in V])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 508, in <listcomp>
    return max([v.wrapOn(canv,aW,aH)[0] for v in V])
                ^^^^^^^^
AttributeError: 'str' object has no attribute 'wrapOn'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 68, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 55, in generate_pdf
    pdf.build([table])
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1082, in build
    self.handle_flowable(flowables)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 931, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/frames.py", line 169, in _add
    w, h = flowable.wrap(aW, h)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 1317, in wrap
    self._calc(availWidth, availHeight)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 732, in _calc
    self._calc_height(availHeight,availWidth,W=W)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 656, in _calc_height
    dW,t = self._listCellGeom(v,w or self._listValueWidth(v),s)
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 508, in _listValueWidth
    return max([v.wrapOn(canv,aW,aH)[0] for v in V])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 508, in <listcomp>
    return max([v.wrapOn(canv,aW,aH)[0] for v in V])
                ^^^^^^^^
AttributeError: 'str' object has no attribute 'wrapOn'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 68, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 39, in generate_pdf
    mytable.append(datas[e])
                   ~~~~~^^^
TypeError: unhashable type: 'dict'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 68, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 55, in generate_pdf
    pdf.build(table)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1057, in build
    flowableCount = len(flowables)
                    ^^^^^^^^^^^^^^
TypeError: object of type 'Table' has no len()
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 68, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 55, in generate_pdf
    pdf.build(table)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1057, in build
    flowableCount = len(flowables)
                    ^^^^^^^^^^^^^^
TypeError: object of type 'Table' has no len()
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 69, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 56, in generate_pdf
    pdf.build(table)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1057, in build
    flowableCount = len(flowables)
                    ^^^^^^^^^^^^^^
TypeError: object of type 'Table' has no len()
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 69, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 56, in generate_pdf
    pdf.build([table])
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1082, in build
    self.handle_flowable(flowables)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 931, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/frames.py", line 169, in _add
    w, h = flowable.wrap(aW, h)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 1317, in wrap
    self._calc(availWidth, availHeight)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 732, in _calc
    self._calc_height(availHeight,availWidth,W=W)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 656, in _calc_height
    dW,t = self._listCellGeom(v,w or self._listValueWidth(v),s)
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 508, in _listValueWidth
    return max([v.wrapOn(canv,aW,aH)[0] for v in V])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 508, in <listcomp>
    return max([v.wrapOn(canv,aW,aH)[0] for v in V])
                ^^^^^^^^
AttributeError: 'str' object has no attribute 'wrapOn'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 70, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 57, in generate_pdf
    pdf.build([table])
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1082, in build
    self.handle_flowable(flowables)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 931, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/frames.py", line 169, in _add
    w, h = flowable.wrap(aW, h)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 1317, in wrap
    self._calc(availWidth, availHeight)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 732, in _calc
    self._calc_height(availHeight,availWidth,W=W)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 656, in _calc_height
    dW,t = self._listCellGeom(v,w or self._listValueWidth(v),s)
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 508, in _listValueWidth
    return max([v.wrapOn(canv,aW,aH)[0] for v in V])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 508, in <listcomp>
    return max([v.wrapOn(canv,aW,aH)[0] for v in V])
                ^^^^^^^^
AttributeError: 'str' object has no attribute 'wrapOn'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 67, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 31, in generate_pdf
    logger.debug("hi")
    ^^^^^^
NameError: name 'logger' is not defined
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 70, in calculation
    generate_pdf(all_data)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 50, in generate_pdf
    ('GRID', (0, 0), (-1, -1), 1, colors.grey)
TypeError: 'tuple' object is not callable
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 80, in calculation
    response = FileResponse(mypdf)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 494, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 444, in __init__
    self.streaming_content = streaming_content
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 466, in streaming_content
    self._set_streaming_content(value)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 499, in _set_streaming_content
    return super()._set_streaming_content(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 470, in _set_streaming_content
    self._iterator = iter(value)
                     ^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 80, in calculation
    response = FileResponse(mypdf)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 494, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 444, in __init__
    self.streaming_content = streaming_content
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 466, in streaming_content
    self._set_streaming_content(value)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 499, in _set_streaming_content
    return super()._set_streaming_content(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 470, in _set_streaming_content
    self._iterator = iter(value)
                     ^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 80, in calculation
    response = FileResponse(mypdf)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 494, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 444, in __init__
    self.streaming_content = streaming_content
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 466, in streaming_content
    self._set_streaming_content(value)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 499, in _set_streaming_content
    return super()._set_streaming_content(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/http/response.py", line 470, in _set_streaming_content
    self._iterator = iter(value)
                     ^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 81, in calculation
    mypdf = generate_pdf(all_data)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 68, in generate_pdf
    pdf.safe()
    ^^^^^^^^
AttributeError: 'SimpleDocTemplate' object has no attribute 'safe'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 76, in calculation
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/forms/forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/forms/forms.py", line 200, in errors
    self.full_clean()
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/forms/forms.py", line 439, in full_clean
    self._post_clean()
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/forms/models.py", line 492, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1445, in full_clean
    self.clean_fields(exclude=exclude)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1497, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 756, in clean
    self.run_validators(value)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 708, in run_validators
    v(value)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/models.py", line 9, in validate_integer_only
    if not value.isnumeric():
           ^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'isnumeric'
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 76, in calculation
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/forms/forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/forms/forms.py", line 200, in errors
    self.full_clean()
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/forms/forms.py", line 439, in full_clean
    self._post_clean()
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/forms/models.py", line 492, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1445, in full_clean
    self.clean_fields(exclude=exclude)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1497, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 756, in clean
    self.run_validators(value)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 708, in run_validators
    v(value)
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/models.py", line 9, in validate_integer_only
    if not value.isnumeric():
           ^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'isnumeric'
/Users/dbond2/Desktop/premieretest-master/mycalc/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/lib/colors.py", line 928, in __call__
    return HexColor(arg)
           ^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/lib/colors.py", line 387, in HexColor
    val = int(val,b)
          ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'colors.grey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 88, in calculation
    pdf_name = generate_pdf(all_data)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 75, in generate_pdf
    pdf.build([table])
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1082, in build
    self.handle_flowable(flowables)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 931, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/frames.py", line 212, in _add
    flowable.drawOn(canv, self._x + self._leftExtraIndent, y, _sW=aW-w)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/flowables.py", line 112, in drawOn
    self._drawOn(canvas)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/flowables.py", line 93, in _drawOn
    self.draw()#this is the bit you overload
    ^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 2299, in draw
    self._drawLines()
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 1229, in _drawLines
    getattr(self,_LineOpMap.get(op, '_drawUnknown' ))( (sc, sr), (ec, er), weight, color, count, space)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 1290, in _drawHLinesB
    self._drawHLines((sc, sr+1), (ec, er+1), weight, color, count, space)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 1274, in _drawHLines
    self._prepLine(weight, color)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 1262, in _prepLine
    self.canv.setStrokeColor(color)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/pdfgen/textobject.py", line 131, in setStrokeColor
    self.setStrokeColor(toColor(aColor))
                        ^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/lib/colors.py", line 931, in __call__
    raise ValueError('Invalid color value %r' % arg)
ValueError: Invalid color value 'colors.grey'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 90, in calculation
    pdf_name = generate_pdf(all_data)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 72, in generate_pdf
    canvas = pdf.canvas
             ^^^^^^^^^^
AttributeError: 'SimpleDocTemplate' object has no attribute 'canvas'
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 103, in calculation
    pdf_name = generate_pdf(all_data)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 90, in generate_pdf
    pdf.build([image, spacer, table, spacer].extend(dishes))
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1057, in build
    flowableCount = len(flowables)
                    ^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 104, in calculation
    pdf_name = generate_pdf(all_data)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 90, in generate_pdf
    pdf.build([image, spacer, table, spacer].extend(dishes))
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1317, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/doctemplate.py", line 1057, in build
    flowableCount = len(flowables)
                    ^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 112, in calculation
    pdf_name = generate_pdf(all_data)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 94, in generate_pdf
    dishes_table = Table(dishes, colWidths=100, rowHeights=100)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 306, in __init__
    self._cellvalues = data = self.normalizeData(data)
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 400, in normalizeData
    outRow = [normCell(cell) for cell in row]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Image' object is not iterable
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 119, in calculation
    pdf_name = generate_pdf(all_data)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 99, in generate_pdf
    dishes_table = Table([dishes], colWidths=colWidths, rowHeights=rowHeights)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/tables.py", line 287, in __init__
    raise ValueError(f'{self.identity()} must have at least a row and column')
ValueError: <Table@0x104AEDDD0 1 rows x 0 cols>... must have at least a row and column
/Users/dbond2/Desktop/premieretest-master/mycalc/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/lib/utils.py", line 523, in open_for_read
    return open_for_read_by_name(name,mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/lib/utils.py", line 463, in open_for_read_by_name
    return open(name,mode)
           ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'images/soup_okroshka.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/lib/utils.py", line 530, in open_for_read
    return BytesIO((datareader if name[:5].lower()=='data:' else rlUrlRead)(name))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/lib/utils.py", line 476, in rlUrlRead
    return urlopen(name).read()
           ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 503, in open
    req = Request(fullurl, data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 322, in __init__
    self.full_url = url
    ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 348, in full_url
    self._parse()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'images/soup_okroshka.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 119, in calculation
    pdf_name = generate_pdf(all_data)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/mycalc/views.py", line 58, in generate_pdf
    image = Image(imagename)
            ^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/platypus/flowables.py", line 424, in __init__
    f = open_for_read(filename, 'b')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dbond2/Desktop/premieretest-master/venv/lib/python3.11/site-packages/reportlab/lib/utils.py", line 532, in open_for_read
    raise IOError('Cannot open resource "%s"' % name)
OSError: Cannot open resource "images/soup_okroshka.jpg"
